### ISSUE TITLE
Memory access error when trying to download a file

### ISSUE THREAD

**Issue by ialexreis** [weizhonzhen/FastHtmlToPdf#1]
Hello there!

I'm currently developing a solution which uses this package in order to create a pdf file, using html views.

To create the file, I developed a preview view that has a download button which will trigger the pdf generation. I tried to generate the pdf three times with the following behaviour:
1. Generated pdf well formated and with all the pages
2. Generated pdf with the raw html string in each page
3. An exception was sent with the message: **"
AccessViolationException: Attempted to read or write to protected memory. This is usually an indication that there is another damaged memory."**

I tried the same application with a diferent htmltopdf converter and the result was always successfull.

### STEPS TO REPRODUCE

1. Windows 10 
2. .NET Framework 4.8
3. Fast.HtmlToPdf.Core  v2.1.0 (nuget package)
4. ASP.NET MVC Solution

### CODE THAT IS CAUSING THE PROBLEM

I tried the following implementations:

```c#
        public FileResult Download(Guid id, String body)
        {
            var pdf = new HtmlToPdf();
            var doc = new PdfDocument();
            var bytes = pdf.Convert(doc, body);

            FileResult file = new FileContentResult(bytes, "application/pdf");
            file.FileDownloadName = id.ToString() + ".pdf";
            pdf.Dispose();
            return File(bytes, System.Net.Mime.MediaTypeNames.Application.Octet, file.FileDownloadName); 
        }


        public FileResult Download(Guid id, String body)
        {
            using (var pdf = new HtmlToPdf())
            {
                var doc = new PdfDocument();
                var bytes = pdf.Convert(doc, body);


                FileResult file = new FileContentResult(bytes, "application/pdf");
                file.FileDownloadName = id.ToString() + ".pdf";

                return File(bytes, System.Net.Mime.MediaTypeNames.Application.Octet, file.FileDownloadName);

            }
        }
```

If you will maintain this project or at least accepting community suggestions please respond to this issue!
I'm here to help!

Greetings! 💯

**Comment by weizhonzhen** [comment]
Fast.HtmlToPdf v48.2.1  (nuget package)
this not bug 
Fast.HtmlToPdf.Core have bug It's been discovered

**Comment by weizhonzhen** [comment]
this bug in Fast.HtmlToPdf.Core v2.2.0 (nuget package) solve
Fast.HtmlToPdf v48.?.? for NET Framework 4.8
Fast.HtmlToPdf v47.?.? for NET Framework 4.7
Fast.HtmlToPdf v46.?.? for NET Framework 4.6
Fast.HtmlToPdf v45.?.? for NET Framework 4.5

but Fast.HtmlToPdf.Core greater than v2.2 have support NET Framework

**Comment by ialexreis** [comment]
If you want to keep this project and make it more "wide", i highly recommend you to add a multitargeting support and instead of having to double the package, you only will support one code structure.

Your package has a lot of potencial and I recommend you to take a look to this: 
1. https://docs.microsoft.com/en-us/nuget/create-packages/multiple-target-frameworks-project-file
2. https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/cross-platform-targeting
